apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  POSTGRES_PASSWORD: UGcjMTIz
  POSTGRES_USER: a3ViZW5ld3M=
  POSTGRES_DB: a3ViZW5ld3M=
  DB_PASSWORD: UGcjMTIz
  DB_USERNAME: a3ViZW5ld3M=
  DB_DATABASE: a3ViZW5ld3M=
  DB_HOST: cG9zdGdyZXNxbA==
