apiVersion: apps/v1
kind: Deployment
metadata:
  name: caos-simulator
spec:
  replicas: 1
  selector:    
    matchLabels:
      app: caos-simulator
  template:
    metadata:
      labels:
        app: caos-simulator
    spec:
      containers:
      - name: caos-simulator
        image: kubedevio/simulador-do-caos:v1
        ports:
        - containerPort: 3000
        #definindo recursos do container
        # limits = requests => QoS = Guaranteed
        resources:
          limits :
            cpu: "0.2"
            memory: 128Mi
          requests:
            cpu: "0.2"
            memory: 128Mi
        #criando uma livenessProbe para verificar se a aplicação está saudável
        #livenessProbe usando o método httpGet para verificar a rota /health
        livenessProbe:
          httpGet:
            port: 3000
            path: /health
            httpHeaders:
            - name: token
              value: "true"
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1
          successThreshold: 1
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: caos-simulator
spec:
  selector:
    app: caos-simulator
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000