apiVersion: apps/v1
kind: Deployment
metadata:
  name: caos-simulator
spec:
  selector:
    matchLabels:
      app: caos-simulator
  template:
    metadata:
      labels:
        app: caos-simulator
    spec:
      containers:
      - name: caos-simulator
        image: registry.k8s.io/busybox
        command:
          - bin/sh
          - -c
        args:
          - touch /tmp/healthy; sleep 600;
        ports:
        - containerPort: 3000
        #criando uma livenessProbe para verificar se a aplicação está saudável
        #livenessProbe usando o método exec para verificar a existência do arquivo /tmp/healthy
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy         
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1
          successThreshold: 1
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: caos-simulator
spec:
  selector:
    app: caos-simulator
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000