apiVersion: apps/v1
kind: Deployment
metadata:
  name: caos-simulator
spec:
  selector:
    matchLabels:
      app: caos-simulator
  template:
    metadata:
      labels:
        app: caos-simulator
    spec:
      containers:
      - name: caos-simulator
        image: registry.k8s.io/goproxy:0.1

        ports:
        - containerPort: 8080
        #criando uma livenessProbe para verificar se a aplicação está saudável
        #livenessProbe usando o método tcpSocket para verificar a porta 8080
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1
          successThreshold: 1
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: caos-simulator
spec:
  selector:
    app: caos-simulator
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000