apiVersion: apps/v1
kind: Deployment
metadata:
  name: caos-simulator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caos-simulator
  template:
    metadata:
      labels:
        app: caos-simulator
    spec: 
      containers:
      - name: caos-simulator
        image: kubedevio/simulador-do-caos:v1
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            port: 3000
            path: /ready
            httpHeaders:
              - name: token
                value: gdffsf
          initialDelaySeconds: 3
          periodSeconds: 4
          failureThreshold: 1
          successThreshold: 1
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: caos-simulator
spec:
  selector:
    app: caos-simulator
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000