apiVersion: apps/v1
kind: Deployment
metadata:
  name: caos-simulator
spec:
  selector:
    matchLabels:
      app: caos-simulator
  template:
    metadata:
      labels:
        app: caos-simulator
    spec:
      containers:
      - name: caos-simulator
        image: kubedevio/simulador-do-caos:v1
        ports:
        - containerPort: 3000
        startupProbe:
          httpGet:
            port: 3000
            path: /health
          failureThreshold: 30
          periodSeconds: 10  
---
apiVersion: v1
kind: Service
metadata:
  name: caos-simulator
spec:
  selector:
    app: caos-simulator
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000